(function() {var implementors = {};
implementors["evolution"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution/object/struct.Card.html\" title=\"struct evolution::object::Card\">Card</a>",synthetic:false,types:["evolution::object::card::Card"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"evolution/object/enum.Trait.html\" title=\"enum evolution::object::Trait\">Trait</a>",synthetic:false,types:["evolution::object::traits::Trait"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution/silly/struct.RankedFeedChoice.html\" title=\"struct evolution::silly::RankedFeedChoice\">RankedFeedChoice</a>&lt;'a&gt;",synthetic:false,types:["evolution::silly::ranked_feed_choice::RankedFeedChoice"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution/silly/struct.RankedSpecies.html\" title=\"struct evolution::silly::RankedSpecies\">RankedSpecies</a>&lt;'a&gt;",synthetic:false,types:["evolution::silly::ranked_species::RankedSpecies"]},];
implementors["evolution_wire"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.FoodValue.html\" title=\"struct evolution_wire::FoodValue\">FoodValue</a>",synthetic:false,types:["evolution_wire::food_value::FoodValue"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.Integer.html\" title=\"struct evolution_wire::Integer\">Integer</a>",synthetic:false,types:["evolution_wire::integer::Integer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.NatPlus.html\" title=\"struct evolution_wire::NatPlus\">NatPlus</a>",synthetic:false,types:["evolution_wire::nat_plus::NatPlus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.Nat.html\" title=\"struct evolution_wire::Nat\">Nat</a>",synthetic:false,types:["evolution_wire::nat::Nat"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.NaturalPlus.html\" title=\"struct evolution_wire::NaturalPlus\">NaturalPlus</a>",synthetic:false,types:["evolution_wire::natural_plus::NaturalPlus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"evolution_wire/struct.Natural.html\" title=\"struct evolution_wire::Natural\">Natural</a>",synthetic:false,types:["evolution_wire::natural::Natural"]},];
implementors["log"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"log/enum.LogLevel.html\" title=\"enum log::LogLevel\">LogLevel</a>",synthetic:false,types:["log::LogLevel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"log/enum.LogLevelFilter.html\" title=\"enum log::LogLevelFilter\">LogLevelFilter</a>",synthetic:false,types:["log::LogLevelFilter"]},];
implementors["serde"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"serde/bytes/struct.Bytes.html\" title=\"struct serde::bytes::Bytes\">Bytes</a>&lt;'a&gt;",synthetic:false,types:["serde::bytes::Bytes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"serde/bytes/struct.ByteBuf.html\" title=\"struct serde::bytes::ByteBuf\">ByteBuf</a>",synthetic:false,types:["serde::bytes::ByteBuf"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
