#!/bin/bash

if ! [ -d rust_bin ]
then
    wget https://static.rust-lang.org/dist/2016-02-02/rust-nightly-x86_64-unknown-linux-gnu.tar.gz -O rust.tar.gz
    mkdir rust_bin
    tar -zxf rust.tar.gz -C rust_bin
fi
    
rust_bin/rust-nightly-x86_64-unknown-linux-gnu/cargo/bin/cargo build
exec ./target/debug/server
